# Generated by Django 5.2.15 on 2026-07-20 21:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RouteDiagnostic",
            fields=[
                ("request_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("provider", models.CharField(max_length=50)),
                ("engine_version", models.CharField(blank=True, max_length=100)),
                ("graph_build_id", models.CharField(blank=True, max_length=100)),
                ("osm_data_date", models.CharField(blank=True, max_length=50)),
                ("costing_profile", models.CharField(max_length=50)),
                ("road_priority", models.CharField(max_length=50)),
                ("units", models.CharField(max_length=20)),
                ("fallback_used", models.BooleanField(default=False)),
                ("request_payload", models.JSONField()),
                ("route_payload", models.JSONField()),
                ("exact_diagnostics", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="RouteIssueReport",
            fields=[
                ("report_id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("route_request_id", models.CharField(blank=True, db_index=True, max_length=100)),
                ("reporter_fingerprint", models.CharField(db_index=True, max_length=64)),
                ("category", models.CharField(max_length=50)),
                ("metadata", models.JSONField()),
                ("summary", models.JSONField()),
                ("consented_location_data", models.JSONField(default=dict)),
                ("location_consent", models.BooleanField(default=False)),
                ("dedupe_key", models.CharField(max_length=64, unique=True)),
                ("incident_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
    ]
