# Generated by Django 5.2.15 on 2026-07-24 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0002_privacy_conscious_route_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedDrive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.UUIDField(db_index=True, editable=False)),
                ('completion_id', models.CharField(editable=False, max_length=100)),
                ('payload_fingerprint', models.CharField(editable=False, max_length=64)),
                ('vehicle_name_snapshot', models.CharField(blank=True, max_length=100)),
                ('route_title_snapshot', models.CharField(blank=True, max_length=200)),
                ('route_id', models.CharField(blank=True, max_length=100)),
                ('mode', models.CharField(choices=[('solo', 'Solo'), ('group', 'Group')], max_length=20)),
                ('group_id', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('elapsed_seconds', models.PositiveIntegerField()),
                ('moving_seconds', models.PositiveIntegerField()),
                ('stopped_seconds', models.PositiveIntegerField()),
                ('actual_distance_metres', models.DecimalField(decimal_places=3, max_digits=12)),
                ('planned_distance_metres', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('average_overall_speed_mps', models.DecimalField(decimal_places=3, max_digits=8)),
                ('average_moving_speed_mps', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('completion_reason', models.CharField(choices=[('arrived', 'Arrived'), ('manually_ended', 'Manually ended'), ('group_ended', 'Group ended'), ('cancelled', 'Cancelled'), ('recovered_completion', 'Recovered completion')], max_length=30)),
                ('reroute_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('off_route_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-finished_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='VehicleProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_id', models.UUIDField(db_index=True, editable=False)),
                ('display_name', models.CharField(max_length=100)),
                ('make', models.CharField(blank=True, max_length=80)),
                ('model', models.CharField(blank=True, max_length=80)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('registration_value', models.CharField(blank=True, max_length=32)),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('plug_in_hybrid', 'Plug-in hybrid'), ('electric', 'Electric'), ('other', 'Other')], max_length=30)),
                ('vehicle_category', models.CharField(choices=[('motorcycle', 'Motorcycle'), ('small_car', 'Small car'), ('medium_car', 'Medium car'), ('large_car', 'Large car'), ('suv', 'SUV'), ('van', 'Van'), ('other', 'Other')], max_length=30)),
                ('tank_capacity_litres', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('battery_capacity_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('typical_mpg_uk', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('typical_litres_per_100km', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('economy_baseline_source', models.CharField(choices=[('user_entered', 'User entered'), ('generic_vehicle_profile', 'Generic vehicle profile'), ('none', 'None')], default='none', max_length=40)),
                ('is_default', models.BooleanField(default=False)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-is_default', 'display_name', 'id'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('owner_id',), name='unique_default_vehicle_per_owner')],
            },
        ),
        migrations.CreateModel(
            name='FuelEconomyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_name_snapshot', models.CharField(blank=True, max_length=100)),
                ('fuel_used_litres', models.DecimalField(decimal_places=4, max_digits=8)),
                ('calculation_method', models.CharField(choices=[('vehicle_profile_estimate', 'Vehicle profile estimate'), ('fuel_level_estimate', 'Fuel level estimate'), ('fuel_used_entry', 'Fuel used entry'), ('fill_to_fill', 'Fill to fill'), ('obd_measured', 'OBD measured')], max_length=40)),
                ('estimated', models.BooleanField()),
                ('start_fuel_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('end_fuel_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tank_capacity_litres_snapshot', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('economy_model_version', models.CharField(blank=True, max_length=30)),
                ('baseline_source', models.CharField(blank=True, max_length=40)),
                ('calculated_mpg_uk', models.DecimalField(decimal_places=4, max_digits=9)),
                ('calculated_litres_per_100km', models.DecimalField(decimal_places=4, max_digits=9)),
                ('explanation', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_drive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_record', to='routing.completeddrive')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_records', to='routing.vehicleprofile')),
            ],
        ),
        migrations.AddField(
            model_name='completeddrive',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_drives', to='routing.vehicleprofile'),
        ),
        migrations.AddIndex(
            model_name='completeddrive',
            index=models.Index(fields=['owner_id', 'finished_at'], name='routing_com_owner_i_2cb753_idx'),
        ),
        migrations.AddConstraint(
            model_name='completeddrive',
            constraint=models.UniqueConstraint(fields=('owner_id', 'completion_id'), name='unique_drive_completion_per_owner'),
        ),
    ]
